# Generated by Django 5.2.5 on 2025-08-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkshortner',
            name='short_code',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
    ]
